version: 0.2
phases:
  pre_build:
    commands:
      # - aws sts get-caller-identity
      # - aws eks update-kubeconfig --region us-east-1 --name py-grpc-cluster
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - sha256sum -c kubectl.sha256
      - openssl sha1 -sha256 kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
      - echo kubectl version --client
      - yum update
      - yum install -y kubectl
      - kubectl get svc
      - kubectl get nodes

  build:
    commands:
      - pwd