version: 0.2
phases:
  pre_build:
    commands:
      # debt
      # installing kubectl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
      - echo kubectl version --client
      #
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region us-east-1 --name py-grpc-cluster
      #
      - kubectl get svc
      - kubectl get nodes

  build:
    commands:
      - pwd