version: 0.2
phases:
  pre_build:
    commands:
      # - aws sts get-caller-identity
      # - aws eks update-kubeconfig --region us-east-1 --name py-grpc-cluster
      - sudo yum install -y kubectl
      - kubectl get svc
      - kubectl get nodes

  build:
    commands:
      - pwd