version: 0.2
phases:
  pre_build:
    commands:
      # installing kubectl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
      - kubectl version --client
      # install aws cli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - yum -y install unzip
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version
      # cluster contex
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      # testing cluster connection
      - kubectl get svc
      - kubectl get nodes

  build:
    commands:
      - pwd